version: '3.3'

services:

   db:
      image: mysql:5.7
      volumes:
        - db_data:/var/lib/mysql
      restart: always
      ports:
      - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: octobercms
        MYSQL_USER: root
        MYSQL_PASSWORD: root
     # build:
      #  context: .
      #  dockerfile: ./compose/mysql/Dockerfile


   octobercms:
     depends_on:
       - db
     image: aspendigital/octobercms:latest
     ports:
       - "80:80"
     volumes:
     - ./htdocs:/var/www/html/
     environment:
       DB_HOST: db:3306
       DB_NAME: octobercms
       DB_USER: root
       DB_PASSWORD: root
       TZ: Europe/Bucharest
volumes:
    db_data:
     

