<?php namespace cris\movies\components;

    use Cms\Classes\ComponentBase;
    use Cris\Movies\Models\Actor;


    class Actors extends ComponentBase{

        public function componentDetails()
        {
            return [
                'name'        => 'Actors',
                'description' => 'Display actor list'
            ];
        }

        public function onRun()
        {
            parent::onRun(); // TODO: Change the autogenerated stub
            $this->page['actors'] = $this->loadActors();

        }

        public function loadActors()
        {

          return  Actor::all();
        }

        private $actors;


    }
